//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzWydarzenRodzinnych.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logowanie
    {
        public int id { get; set; }
        public string Nazwa { get; set; }
        public string Haslo { get; set; }
        public Nullable<int> id_uzytkownik { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
