//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzWydarzenRodzinnych.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Powiadomienie
    {
        public int id { get; set; }
        public int id_uzytkownik { get; set; }
        public Nullable<int> id_wydarzenie { get; set; }
        public Nullable<int> rodzaj { get; set; }
        [Display(Name = "Data powiadomienia")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Data { get; set; }
        public bool Przeczytana { get; set; }
        public Nullable<int> tmp { get; set; }
        public Nullable<int> id_wpis { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Wpis Wpis { get; set; }
        public virtual Wydarzenie Wydarzenie { get; set; }
    }
}
