//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzWydarzenRodzinnych.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Powiadomienia
    {
        public int id { get; set; }
        public int id_uzytkownik { get; set; }
        public Nullable<int> id_wydarzenie { get; set; }
        public Nullable<int> id_wiadomosc { get; set; }
        public Nullable<int> rodzaj { get; set; }
    
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Wiadomosc Wiadomosc { get; set; }
        public virtual Wydarzenie Wydarzenie { get; set; }
    }
}
