//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzWydarzenRodzinnych.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wpis
    {
        public int id { get; set; }
        public string Opis { get; set; }
        public string Zdjecie { get; set; }
        public Nullable<int> id_wydarzenie { get; set; }
        public Nullable<int> id_przebieg { get; set; }
        public int id_uzytkownik { get; set; }
        public string Tytul { get; set; }
        public System.DateTime data_dodania { get; set; }
    
        public virtual Przebieg Przebieg { get; set; }
        public virtual Wydarzenie Wydarzenie { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
    }
}
