//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzWydarzenRodzinnych.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wydarzenie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wydarzenie()
        {
            this.Powiadomienia = new HashSet<Powiadomienia>();
            this.Powiadomienie = new HashSet<Powiadomienie>();
            this.Przebieg = new HashSet<Przebieg>();
            this.Uczestnicy = new HashSet<Uczestnicy>();
            this.Wpis = new HashSet<Wpis>();
            this.Zadanie = new HashSet<Zadanie>();
            this.Zaproszenie = new HashSet<Zaproszenie>();
        }
    
        public int id { get; set; }
        public string Tytul { get; set; }
        public string Opis { get; set; }
        public System.DateTime DataRozpoczencia { get; set; }
        public System.DateTime DataZakonczenia { get; set; }
        public int id_organizator { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Powiadomienia> Powiadomienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Powiadomienie> Powiadomienie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Przebieg> Przebieg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uczestnicy> Uczestnicy { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wpis> Wpis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zadanie> Zadanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaproszenie> Zaproszenie { get; set; }
    }
}
