//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KalendarzWydarzenRodzinnych.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Zadanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zadanie()
        {
            this.ZadanieUczestnik = new HashSet<ZadanieUczestnik>();
        }
    
        public int id { get; set; }
        [Display(Name = "Nazwa")]
        public string Zadanie1 { get; set; }
        public int id_wydarzenie { get; set; }
        [Display(Name = "Liczba uczestników")]
        public Nullable<int> liczba_uczestnikow { get; set; }
    
        public virtual Wydarzenie Wydarzenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZadanieUczestnik> ZadanieUczestnik { get; set; }
    }
}
